PremiosWeb/PremiosWeb/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls', include('polls.urls')),
]

PremiosWeb/polls/urls.py
from django.urls import path

from . import views

app_name='polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('/<response_id>/detail', views.detail, name='detail'),
    path('/<response_id>/result', views.result, name='result'),
    path('/<response_id>/vote', views.vote, name='votes'),
]

PremiosWeb/polls/models.py
from datetime import timedelta
from django.db import models
from django.utils import timezone 

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def time_antique(self):
        return timezone.now() >= self.pub_date >= timezone.now() - timedelta(days=1)

class Choise(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE) 
    choise_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choise_text

PremiosWeb/polls/views.py
from django.utils import timezone
from unittest import expectedFailure
from urllib import response
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Choise, Question
from django.views import generic

# Create your views here.

def index(request):
    questions = Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
    context = {
        'questions': questions,
    }
    return render(request, 'polls/index.html', context) 

# class IndexView(generic.ListView):
#     template_name = 'polls/index.html'
#     context_object_name = 'questions'

#     def get_queryser(self):
#         """return the last five published questions"""
#         return Question.objects.order_by('-pub_date')[:5]


def detail(request, response_id):
    # question = get_object_or_404(Question,pk=response_id)
    question = Question.objects.filter(pub_date__lte=timezone.now()).get(pk=response_id)
    context = {
        'question': question,
    }
    return render(request, 'polls/detail.html', context) 


# class DetailView(generic.DetailView):
#     model = Question
#     template_name = 'polls/detail.html'

#     def  get_queryset(self):
#         return Question.objects.filter(pub_date__lte=timezone.now())


def result(request, response_id):
    question = Question.objects.filter(pub_date__lte=timezone.now()).get(pk=response_id)
    return render(request, 'polls/result.html', {
        "question": question,
        'response_id': response_id,
    })

# class ResultView(generic.DetailView):
#     model = Question
#     template_name = 'polls/result.html'

#     def get_queryset(self):
#         return Question.objects.filter(pub_date__lte=timezone.now())



def vote(request, response_id):
    question = get_object_or_404(Question, pk=response_id)
    try:
        find_choise = question.choise_set.get(pk=request.POST['choise'])
    except (KeyError, Choise.DoesNotExist):
        return render(request,'polls/detail.html', {
            'question': question,
            'error_message': "no elegiste ninguna respuesta"
        })
    else:
        find_choise.votes += 1
        find_choise.save()
        return HttpResponseRedirect(reverse("polls:result", args=(response_id)))


# def vote(request, response_id):
#     question = get_object_or_404(Question, pk=response_id)
#     try:
#         selected_choise = question.choise_set.get(pk=request.POST['choise'])
#     except (KeyError,Choise.DoesNotExist):
#         return render(request,'polls/detail.html', {
#             "question": question,
#             "error_message": "no elegiste ningun valor",
#         })
#     else:
#         selected_choise.votes += 1
#         selected_choise.save()
#         return HttpResponseRedirect(reverse("polls:result", args=(response_id,)))

PremiosWeb/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pokemon/Detail</title>
</head>
<body>
    <header>

    </header>
    <main>
        <form action="{% url 'polls:votes' question.id %}" method="post">
            {% csrf_token %}
            <fieldset>
                <legend><h1>{{ question.question_text }}</h1></legend>
                {% if error_message %}
                    
                    <p><strong>{{ error_message }}</strong></p>
            
                {% endif %}
                {% for choise in question.choise_set.all %}
                    <input 
                        type="radio"
                        name='choise'
                        id="choise{{ forloop.counter }}"
                        value="{{ choise.id }}"
                    >
                    <label for="choise{{ forloop.counter }}">
                        {{ choise.choise_text }}
                    </label>
                    <br>
                {% endfor %}
            </fieldset>
            <input type="submit" value="votar">
        </form>
            
    </main>
    <footer>

    </footer>
</body>
</html>






{% comment %} <h1>{{ question.question_text }}</h1>


<ul>
    {% for choise in question.choise_set.all %}
        <li>
            <a href="{% url 'polls:votes' choise.id %}">
                {{ choise }}
            </a>
        </li>
    {% endfor %}
</ul> {% endcomment %}

PremiosWeb/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Votes Pokemon</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/StylePolls.css' %}">
</head>
<body>
    <header>
        <h1>Premios Pokemon</h1>
    </header>
    <main>
        

        {% if questions %}
            <ul>
                {% for question in questions %}
                    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>sorry, Questions not found :(</p>    
        {% endif %}
    </main>
    <footer>
        <a href="#">Contacto</a>
        <a href="#">informacion</a>
        <a href="#">terminos y condiciones</a>
    </footer>
</body>
</html>

{% comment %} 
{% load static %}
<link rel="stylesheet" href="{% static 'css/StylePolls.css' %}">

{% if questions %}
    <ul>
        {% for question in questions %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>sorry, Questions not found :(</p>
{% endif %} {% endcomment %}

PremiosWeb/polls/templates/polls/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pokemon/Result</title>
</head>
<body>
    <header>
        <h1>{{question.question_text}}</h1>
    </header>
    <main>
        {% for choise in question.choise_set.all %}
            <ul>
                <li>
                    {{choise.choise_text}} --- {{ choise.votes }} vote{{choise.votes|pluralize}}
                </li>
            </ul>
        {% endfor %}
        <a href="{% url 'polls:detail' response_id %}">volver a votar</a>
    </main>
    <footer>

    </footer>
</body>
</html>